# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://__MYSQL_IP0__:__MYSQL_PORT__/devops_ci_repository?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: __MYSQL_USER__
    password: __MYSQL_PASS__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21916
server:
  port: __BKCI_REPOSITORY_API_PORT__

# github repository
github:
  clientId: __GITHUB_CLIENT_ID__
  clientSecret: __GITHUB_CLIENT_SECRET__
  callbackUrl: https://__BKCI_FQDN__:__BKCI_HTTP_PORT__/external/api/external/github/oauth/callback
  redirectUrl: http://__BKCI_FQDN__:__BKCI_HTTP_PORT__/console/codelib
  appUrl: https://github.com/apps/__GITHUB_APP__
  signSecret: __GITHUB_SIGN_SECRET__

#git typo repository
git:
  # many be no work for gitlab
  gitlabUrl: http://__GITLAB_URL__    # or use git repository config
  gitlabApiUrl: http://__GITLAB_URL__/api/v4

#svn open api url
svn:
  apiUrl: http://__SVN_URL__
  apiKey: __SVN_API_KEY__
  webhookApiUrl: http://__SVN_URL__/webhooks