# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devops_ci_artifactory?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: KINGsoft+5688

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21920
server:
  port: 21920

# 以下为构件存储目录，需要做分布式分享
# 如果微服务是部署多机节点，则以下目录需要做成分布式高可用的，比如NFS，CephFS挂载
# 保证多节点都能读取到
artifactory:
  archiveLocalBasePath: /data/bkee/public/artifactory