# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devops_ci_artifactory?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: KINGsoft+5688

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21918
server:
  port: 21918

store:
  profileUrlPrefix: http://
  atomDetailBaseUrl: http://devops.testplus.cn:80/console/store/atomStore/detail/atom/
  templateDetailBaseUrl: http://devops.testplus.cn:80/console/store/atomStore/detail/template/

file:
  allowUploadFileTypes: jpg,png,gif,swf,txt,doc,docx,xls,xlsx,ppt,pptx,pdf,flv,rmvb,mp4,svg
  maxUploadFileSize: 52428800