# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://10.11.82.180:3306/devops_ci_process?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: KINGsoft+5688

server:
  port: 21900

# 以下配置为从其他文件同步而来，用作单实例的部署所用
artifactory:
  archiveLocalBasePath: /data/bkee/public/artifactory

environment:
  agent-package: /data/bkee/bkci/agent-package

elasticsearch:
  ip: 10.11.81.39
  port: 9200

store:
  profileUrlPrefix: http://
  atomDetailBaseUrl: http://devops.testplus.cn:80/console/store/atomStore/detail/atom/
  templateDetailBaseUrl: http://devops.testplus.cn:80/console/store/atomStore/detail/template/

file:
  allowUploadFileTypes: jpg,png,gif,swf,txt,doc,docx,xls,xlsx,ppt,pptx,pdf,flv,rmvb,mp4,svg
  maxUploadFileSize: 52428800

# github repository
github:
  clientId: 
  clientSecret: 
  callbackUrl: https://devops.testplus.cn:80/external/api/external/github/oauth/callback
  redirectUrl: http://devops.testplus.cn:80/console/codelib
  appUrl: https://github.com/apps/用户公司在GitHub上创建的App名称
  signSecret: 用户公司在Github的repo创建的webhook统一的密钥

#git typo repository
git:
  # many be no work for gitlab
  gitlabUrl: http://gitlab网站地址    # or use git repository config
  gitlabApiUrl: http://gitlab网站地址/api/v4

#svn open api url
svn:
  apiUrl: http://SVN地址
  apiKey: SVN的API密钥
  webhookApiUrl: http://SVN地址/webhooks

# 蓝鲸登录平台API地址，对接蓝鲸平台时才需要用到
bk_login:
  path: https://蓝鲸PaaS域名:蓝鲸HTTP端口/api/c/compapi/v2/bk_login/
  getUser: get_user/
  getAllUser: get_all_users/
  bk_app_code: 比如DevOps的AppCode是devops
  bk_app_secret: 对应的Token


logo:
  allowUploadLogoTypes: jpg,png,svg
  allowUploadLogoWidth: 200
  allowUploadLogoHeight: 200
  maxUploadLogoSize: 2097152

aes:
  aesKey: "J%k^yO{?vt}3tXpG"
  aesMock: "******"

cert:
  aes-key: "gHi(xG9Af)jEvCx&"

credential:
  mixer: "******"
  aes-key: "G/I%yP{?ST}2TXPg"

influxdb:
  server: influxDB服务器地址
  userName: influxDB用户名
  password: influxDB用户名