# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devops_ci_repository?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: KINGsoft+5688

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21916
server:
  port: 21916

# github repository
github:
  clientId: 
  clientSecret: 
  callbackUrl: https://devops.testplus.cn:80/external/api/external/github/oauth/callback
  redirectUrl: http://devops.testplus.cn:80/console/codelib
  appUrl: https://github.com/apps/用户公司在GitHub上创建的App名称
  signSecret: 用户公司在Github的repo创建的webhook统一的密钥

#git typo repository
git:
  # many be no work for gitlab
  gitlabUrl: http://gitlab网站地址    # or use git repository config
  gitlabApiUrl: http://gitlab网站地址/api/v4

#svn open api url
svn:
  apiUrl: http://SVN地址
  apiKey: SVN的API密钥
  webhookApiUrl: http://SVN地址/webhooks