# Project Service Template 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devops_ci_project?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: KINGsoft+5688

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21912
server:
  port: 21912

# 蓝鲸登录平台API地址，对接蓝鲸平台时才需要用到
bk_login:
  path: https://蓝鲸PaaS域名:蓝鲸HTTP端口/api/c/compapi/v2/bk_login/
  getUser: get_user/
  getAllUser: get_all_users/
  bk_app_code: 比如DevOps的AppCode是devops
  bk_app_secret: 对应的Token