# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devops_ci_environment?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: KINGsoft+5688

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21919
server:
  port: 21919

environment:
  agent-package: /data/bkee/bkci/agent-package

influxdb:
  server: influxDB服务器地址
  userName: influxDB用户名
  password: influxDB用户名